# Change these first
owner: hegga-cl # Your GitHub organization or username, where this repository lives
repo: findie-upptime # The name of this repository

sites:
  - name: findie prod
    url: https://www.findie.cl/
  - name: api prod
    url: https://api-01.findie.cl/api/v1/freelancers/top_featured/
  - name: findie staging
    url: https://staging.findie.cl/
  - name: api staging
    url: https://api-01.findie.cl/api/v1/freelancers/top_featured/
assignees: # Users to assign downtime issues (optional)
  - EfrainGaray
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /findie-upptime
  logoUrl: https://www.findie.cl/static/media/logo-black.4ed27940.svg
  name: Findie 
  introTitle: "**Monitoreo** Sistema simple de monitoreo para los distintos ambientes."
  introMessage: aca se podran verificar los servicios de findie, a su vez se podran subcribir a notificaciones sobre las posibles caidas.
  navbar:
    - title: Status
      href: /findie-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
